export const FETCH_WORKERS_LIST = 'FETCH_WORKERS_LIST';
export const FETCH_WORKER = 'FETCH_WORKER';

// AUTH
export const LOGIN_IN = 'LOGIN_IN';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

export const REGISTER = 'REGISTER';
export const SET_REGISTER_LOADING = 'SET_REGISTER_LOADING';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';
